### ISSUE TITLE
Idle Cam in vehicles

### ISSUE THREAD

**Issue by ToasterF16** [TayMcKenzieNZ/NoIdleCam#5]
This script only works on foot, we'd also need it to be effective for vehicles:
https://docs.fivem.net/natives/?_0x9E4CFFF989258472

**Comment by TayMcKenzieNZ** [comment]
It does and should work in vehicles, though was made standalone so no idea about any framework conflicts or whatever

**Comment by TayMcKenzieNZ** [comment]
I have gone into my server, used the command to turn the idle cam, and my ped looks around at the world as intended with the idle cam off / resource not started.

I have entered a vehicle with the idle cam off, nothing happens.

I have entered a vehicle with the idle cam off, in first person, nothing happens

**Comment by ToasterF16** [comment]
Try sitting in the front right passenger seat and you'll see the camera still flying around the car after some time with your ressource.

Adding InvalidateVehicleIdleCam() seems to prevent this behaviour too.

**Comment by TayMcKenzieNZ** [comment]
Oh, interesting 🤔

**Comment by TayMcKenzieNZ** [comment]
If you can, feel free to make a PR

**Comment by geekgarage** [comment]
Fixed this in PR #6
